# Site settings
title:
description:
google-plus: # For Google Authorship (if this is to be a multi-author site, an override will need to be added to post front matter.)
twitter: # Site Twitter account or main author's Twitter accout if there is no dedicated site account.
# baseurl: ""
url:

# Jekyll Configuration
# version:
encoding: UTF-8
permalink: /:title/
paginate: 5
paginate_path: "/blog/page/:num/"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Custom Collections
# collections:
#   portfolio:
#     output: true
#     permalink: /portfolio/:title/

# Collection Defaults

defaults:
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page

# Frontmatter Defaults
sidebar_options:
  - sidebar
  - no-sidebar

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json]

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# HTML Compression - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
