# Site settings
title:
description:
google-plus: # For Google Authorship (if this is to be a multi-author site, an override will need to be added to post front matter.)
twitter: # Site Twitter account or main author's Twitter accout if there is no dedicated site account.
# baseurl: ""
url:

# Jekyll configuration
version: 3.0.3
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
sass:
  sass_dir: _sass
  style: compressed
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
- scope:
    path: ""
    type: pages
  values:
    layout: page
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# include: ["_pages"]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "gulpfile.js", "package.json", "_config-dev.yml", "_drafts"]
